### ISSUE TITLE
unable to deploy

### ISSUE THREAD

**Issue by nikszymanis** [alexdunae/jackson2bears#1]
```
   error  build/works/video.html
```

key not found: "video"
/Users/Nik/Sites/jackson2bears/config.rb:8:in `fetch'
/Users/Nik/Sites/jackson2bears/config.rb:8:in`toc'
/Users/Nik/Sites/jackson2bears/source/works/video.haml:7:in `block in singleton class'
/Users/Nik/Sites/jackson2bears/source/works/video.haml:-8:in`instance_eval'
/Users/Nik/Sites/jackson2bears/source/works/video.haml:-8:in `singleton class'
/Users/Nik/Sites/jackson2bears/source/works/video.haml:-10:in`__tilt_70364546066160'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in`evaluate'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/tilt-1.4.1/lib/tilt/haml.rb:24:in `evaluate'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in`render'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/renderers/haml.rb:6:in `render'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/padrino-helpers-0.12.5/lib/padrino/rendering.rb:16:in`render'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/rendering.rb:303:in `render_individual_file'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/rendering.rb:181:in`_render_with_all_renderers'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/rendering.rb:149:in `render_template'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/sitemap/resource.rb:127:in`block in render'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/activesupport-4.1.10/lib/active_support/notifications.rb:161:in `instrument'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/util.rb:41:in`instrument'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/application.rb:219:in `instrument'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/sitemap/resource.rb:14:in`instrument'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/sitemap/resource.rb:100:in `render'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:256:in`process_request'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:206:in `block in call!'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:205:in`catch'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:205:in `call!'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:191:in`call'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/urlmap.rb:66:in `block in call'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in`each'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `call'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-more/extensions/asset_hash.rb:71:in`call'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-more/extensions/minify_javascript.rb:41:in `call'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-more/extensions/minify_css.rb:48:in`call'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-autoprefixer-2.4.3/lib/middleman-autoprefixer/extension.rb:43:in `call'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/head.rb:13:in`call'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/lint.rb:37:in`call'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in`request'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rack-test-0.6.3/lib/rack/test.rb:58:in`get'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/cli/build.rb:255:in `render_to_file'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/cli/build.rb:221:in`build_resource'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/cli/build.rb:213:in `each'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/cli/build.rb:213:in`execute!'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/cli/build.rb:128:in `invoke!'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in`action'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/cli/build.rb:70:in `build'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/cli.rb:72:in`method_missing'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:126:in`run'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/lib/middleman-core/cli.rb:20:in`start'
/Users/Nik/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/middleman-core-3.3.10/bin/middleman:18:in `<top (required)>'
/Users/Nik/.rbenv/versions/2.0.0-p353/bin/middleman:23:in`load'
/Users/Nik/.rbenv/versions/2.0.0-p353/bin/middleman:23:in `<main>'
== Request: /contact.html
== Finishing Request: contact.html (0.0s)
   identical  build/contact.html
There were errors during this build

**Comment by nikszymanis** [comment]
Not sure if this is helpful at all.
